# Generated by Django 3.2 on 2022-07-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_post_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thubnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
