# Generated by Django 3.2 on 2022-07-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_post_thubnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='thubnail',
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
