# Generated by Django 3.2 on 2022-07-07 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220706_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('technology', 'Technology'), ('science', 'Science'), ('sports', 'Sports'), ('entertainment', 'Entertainment'), ('health', 'Health'), ('business', 'Business'), ('politics', 'Politics'), ('world', 'World'), ('education', 'Education'), ('lifestyle', 'Lifestyle'), ('travel', 'Travel'), ('fashion', 'Fashion'), ('food', 'Food'), ('fitness', 'Fitness'), ('style', 'Style'), ('travel', 'Travel'), ('lifestyle', 'Lifestyle')], default='general', max_length=30, verbose_name='post category'),
        ),
    ]
